### ISSUE TITLE
Work with a custom dataset; not the reuters dataset

### ISSUE THREAD

**Issue by bikashg** [lda-project/lda#110]
The reuters dataset (the document term matrix) is already provided in the test data. However, if I need to work with a custom dataset, how would I proceed? What is the process to build a document term matrix from a corpus of text files?

**Comment by zhiaoLee** [comment]
+1

**Comment by bilbof** [comment]
@bikashg as you say, the Reuters dataset is a document term matrix, so I think you can copy that format.

For example, you might have this doc:term matrix for your data in a `data.csv` file:

```csv
doc_id,1,2,3,4,5, ...
doc_1,0,0,5,1,2, ...
doc_2,0,1,2,3,4, ...
```

The following script loads in data in the above format and fits the provided LDA model to that data:

```python
import numpy as np
import lda
import csv

matrix = np.loadtxt(open("data.csv", "rb"), delimiter=",", skiprows=1).astype("int64")
X = matrix[:,1:] # X is training data, matrix is data with doc id

model = lda.LDA(n_topics=100, n_iter=1000, random_state=1)
model.fit(X)
```

To export the model results to a CSV you might do this:

```python
doc_ids = matrix[:,0]
doc_topic = model.doc_topic_

with open('doc_topics.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=',', quoting=csv.QUOTE_MINIMAL)
    writer.writerow(["doc_id", "topic_id"])
    for i, doc_id in enumerate(doc_ids):
        writer.writerow([doc_id, doc_topic[i].argmax()])
```

The above doesn't include the printing the terms for each topic etc., but you get the idea.

**Comment by bilbof** [comment]
By the way, just in case what I wrote above was a bit hard to understand, you can explore the structure of data (like the Reuters example dataset) quite easily with the [Python interpreter](https://docs.python.org/3/tutorial/interpreter.html). For example:

```python
>>> import lda.datasets
>>> X = lda.datasets.load_reuters()
>>> X
array([[1, 0, 1, ..., 0, 0, 0],
       [7, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0]], dtype=int32)
>>> X[0]
array([1, 0, 1, ..., 0, 0, 0], dtype=int32)
>>> len(X[0])
4258
>>> X[0][0]
1
```
