### ISSUE TITLE
ModuleNotFoundError: No module named 'lda._lda'; 'lda' is not a package

### ISSUE THREAD

**Issue by vidushika99** [lda-project/lda#113]
when I tried to run the project I got an error saying ModuleNotFoundError: No module named 'lda._lda'; 'lda' is not a package. and I found a solution from [https://www.programmersought.com/article/48705949273/](url) here and as it says I renamed 'lda' folder. but still I am getting this error. Could you please check on this?

![lda](https://user-images.githubusercontent.com/42301651/99727828-80fb6f00-2ade-11eb-8c25-0eff64f4ef70.PNG)

**Comment by severinsimmler** [comment]
You have to compile it first, because this package is partially written in C via Cython. It's easier if you install the wheel:

```
$ pip install lda
```

**Comment by vidushika99** [comment]
Thank you for your response. I have tried these steps. I tried with the wheel too. but still, I am getting that error. Could you please check on this?

**Comment by severinsimmler** [comment]
Make sure your current directory does not contain the source code or a folder `lda`. Python prefers local over installed packages. And try to set up a new and clean virtual environment where you `pip install` the wheel.

**Comment by vidushika99** [comment]
Thank you. I'll try this

**Comment by HrishikeshGadekar** [comment]
> You have to compile it first, because this package is partially written in C via Cython. It's easier if you install the wheel:
> 
> ```
> $ pip install lda
> ```

Hi @severinsimmler,

I am caught up with the exact same issue. It would be great if you could explain a bit on how exactly to make this cython file work.

**Comment by parth-verma7** [comment]
> You have to compile it first, because this package is partially written in C via Cython. It's easier if you install the wheel:
> 
> ```
> $ pip install lda
> ```

installing lda is also giving up error...

**Comment by HrishikeshGadekar** [comment]
Hi @parth-verma7 ,
Could you share the logs or screenshot of the error to help better?

**Comment by parth-verma7** [comment]
Hi @HrishikeshGadekar 
![image](https://user-images.githubusercontent.com/96720577/196037129-8e30050d-710e-4e85-9d98-84911d3e725b.png)
have a look please, i tried it installing using pip install lda, ad then it showed error

**Comment by HrishikeshGadekar** [comment]
Hi @parth-verma7 ,

Please install Microsoft C++ Build tools. You can find more help here: https://stackoverflow.com/questions/40504552/how-to-install-visual-c-build-tools.

The process is reasonably hectic but ensure you install the build tools successfully. Once you have done so, hopefully, it should install lda. If not, please share the error logs again.

Thank You
