### ISSUE TITLE
Taking over active development or at least maintenance?

### ISSUE THREAD

**Issue by severinsimmler** [lda-project/lda#120]
I use this package quite often, but found out that there are currently no wheels for Python 3.11. Since the project is apparently no longer actively developed, I would offer to at least take care that there are always wheels available for the last few Python versions? Should I just fork the project and open pull requests? If I make the effort, will someone review my PRs and merge them?

I do have some experience with Cython, building wheels etc. – feel free to check out my library `chaine`: https://github.com/severinsimmler/chaine

**Comment by riddella** [comment]
I'd welcome a pull request getting things working (source build) with Python 3.11 and Python 3.12. (I assume you encountered some problems?)

And I'm open to hearing ideas for how to get wheels building in a way that's simple and doesn't require frequent attention. I had thought about getting this working with the new scikit-build -- but not anytime soon.

I'd be glad to add anyone who does serious work on this to the authors list.

**Comment by severinsimmler** [comment]
Awesome, thanks! I'll start working on a PR then :)

**Comment by happypig** [comment]
Any progress about wheel for Python 3.11 or 3.12, thanks in advance.
