### ISSUE TITLE
Any progress about wheel for Python 3.11 or 3.12, thanks in advance.

### ISSUE THREAD

**Issue by happypig** [lda-project/lda#121]
Any progress about wheel for Python 3.11 or 3.12, thanks in advance.

#120

**Comment by severinsimmler** [comment]
Hi @happypig, I actually started working on wheels for newer Python versions again. Was a bit busy the last weeks/months, but try to get a PR ready asap.

**Comment by happypig** [comment]
@severinsimmler 
No sweat! You can do it.

**Comment by severinsimmler** [comment]
See https://github.com/lda-project/lda/pull/122 :)

**Comment by ariddell** [comment]
Done, thanks to @severinsimmler
