### ISSUE TITLE
ModuleNotFoundError: No module named 'lda._lda'

### ISSUE THREAD

**Issue by yurincmt** [lda-project/lda#127]
can anyone help me with it ?

![image](https://github.com/lda-project/lda/assets/62949626/77e26dfa-cb49-45f0-82c3-af220adf4052)

**Comment by ghuls** [comment]
Import it from outside the git repo dir.

**Comment by yurincmt** [comment]
Thanks :)

**Comment by NewLJing** [comment]
> Import it from outside the git repo dir.

Can you explain its detail ?
