### ISSUE TITLE
py312 compatability

### ISSUE THREAD

**Issue by LukeMcWattersCMA** [lda-project/lda#129]
Hi,

I've tried to install your package into my python 3.12 environment (both via pip and conda forge). 

I've been getting some DepreciationError messages when trying to install the package.

Do I need to depreciate my python version to be able to use this package?

Thanks so much

**Comment by FiftySea** [comment]
Hello, I am also Python version 3.12 and cannot install it. Have you resolved the issue

**Comment by LukeMcWattersCMA** [comment]
Not yet - I suspect the package may not be 3.12 compatible. This may take some time. For now I am using sklearn's LDA functionality.

**Comment by ariddell** [comment]
I'd like lda to support Python 3.12. I'll look into this soon.

**Comment by ariddell** [comment]
I just made a release. Please see if it works for you. If not, let me know more details about your platform and the errors you are seeing.

**Comment by ariddell** [comment]
Everything works for me on Ubuntu 23.10 with Python 3.12.

**Comment by FiftySea** [comment]
I am using the Windows operating system, do I need to use another operating system？

**Comment by ariddell** [comment]
lda used to work on Windows. I would hope that nothing has changed.

There are windows wheels on PyPI: https://pypi.org/project/lda/#files

Can you share the error you're seeing when you try to pip install lda?

**Comment by FiftySea** [comment]
Thank you very much. I successfully installed it on Windows through the website you provided.
