### ISSUE TITLE
the version specification of the dependent numpy incorrect?

### ISSUE THREAD

**Issue by b-trout** [lda-project/lda#133]
Hi, thanks to develop such a great library! I am concern that the version specification of the dependent numpy incorrect.

The file`pyproject.toml` says this library requires `numpy>=1.83` and the latest numpy1 is 1.26.4.

Could you modify the version?

**Comment by b-trout** [comment]
This would be typo of `>=1.13.0`

**Comment by ariddell** [comment]
Closed in #134
