### ISSUE TITLE
I got an error when install lda via source code

### ISSUE THREAD

**Issue by novazz** [lda-project/lda#70]
when i downloaded source code and run sudo python setup.py install, I got such error:

Error parsing setup.cfg: Exception: Versioning for this project reqires either an sdist tarball, or access to an uptream git repositoryment given to pbr.version.VersionInfo. Project name lda was given, but was not able to be found.

I am using python 3.5 and centOS 7, I have numpy 1.13.1 and pbr 3.1.1 installed and have already run "make cython". I cannot install lda via "pip install lda" because my computer is offline.

so how can I solve this problem? thanks a lot

**Comment by ariddell** [comment]
Is there a reason you can't download and install the wheel directly? It's more or less guaranteed to work :)

This one should work on centOS 7: lda-1.0.5-cp35-cp35m-manylinux1_x86_64.whl (from https://pypi.python.org/pypi/lda )

**Comment by novazz** [comment]
thanks so much for your help. I downloaded source code from https://pypi.python.org/pypi/lda and successfully installed lda by sudo python setup.py install, but I still got another error:

import lda.datasets

ImportError: No module named 'lda.datasets'; 'lda' is not a package

Is there anything i missed? how to fix it?
thanks again

**Comment by yanshengjia** [comment]
Met the same issue!

**Comment by riddella** [comment]
Can you ``import lda`` at all? If you can't, it's likely that running ``python3 setup.py install`` did not work. In this case, you might post the errors there.

**Comment by ariddell** [comment]
Are you able to ``import lda`` at all?

Again, if you can, I'd recommend just installing the wheel from PyPI. Installing the wheel is more likely to work and is, in any event, faster.
