### ISSUE TITLE
transformed document sum can exceed 1 (by a lot..)

### ISSUE THREAD

**Issue by patrickmesana** [lda-project/lda#71]
I just ran 2000 iterations on a dataset of very short texts and I get  values higher than 1e+300 and some very low negative values. About 1% of transformed documents do not sum to 1.
I did not investigate yet but I am surprised nobody had this issue before. I managed to train successfully many models before with the exact same parameters, so I am guessing a normalisation problem!?

I had the  issue on Ubuntu 16.04 python 3.6, I can't reproduce on my Macbook Pro python 3.6 as well.

**Comment by patrickmesana** [comment]
This issues appeared on Ubuntu 16.04. I tried the same code on my macbook pro and no problem at all, all documents are normalized and have "normal" values. Maybe it's just a default configuration on Linux.

**Comment by ariddell** [comment]
Thanks for the report. You can look at the unnormalized latent variable frequencies in ``self.nzw_``. This might suggest what is going on.

What version of Python are you using?

**Comment by patrickmesana** [comment]
3.6

**Comment by patrickmesana** [comment]
I was going to look at self.nzw_ :) compare the values between the 2 environements

**Comment by patrickmesana** [comment]
I checked the nzw values, they seem fine in both models. I compared min (=0), max and average, they are very close between both models, the working one (MBP) and the failing one (Linux). So something is happening during document transformation or maybe normalisation.

**Comment by ariddell** [comment]
If all else fails and you have a fitted model where the error is occurring, you could pickle it and email it to me.

**Comment by patrickmesana** [comment]
I tracked the documents that are problematic and it's 1 or 2 words documents where the transformation components are almost 0 everywhere. I don't think a lot of people try LDA on 1 or 2 words documents but it correspond to  0.1% of my documents after I pretreat them. I know LDA is not well fitted for very short text but it was an experiment. The interesting note here, one good example, is on the model trained on my Mac, components are all 0s and on the one trained on Linux, all 0s except one component extremely high and another extremely low. The "Linux model" is actualy more right because the associated topic does make sense... I will move on to other models now, maybe I will investigate more later.
