### ISSUE TITLE
add verbose and tolerance feature

### ISSUE THREAD

**Issue by jmcamac** [lda-project/lda#95]
The verbose feature would allow a user to specify whether or not they want the log likelihood messages. Also, the tolerance feature would allow the user to end Gibbs sampling early - not execute all iterations - once a desired tolerance level has been reached. Here's a branch with those changes: https://github.com/jmcamac/lda/tree/develop/lda

**Comment by ariddell** [comment]
I'm more than happy to consider these changes. (They do seem like two distinct changes.)

When `lda` was written, there was not a standard method in the community for reporting progress in a (very) long-running  calculation. If one has emerged (e.g., for scikit-learn or something similar), I'll happily adopt it.

You can disable the logging output using the `logging` module. If documentation doesn't describe how to do this, that's a bug.

**Comment by ariddell** [comment]
The logging setup is a mess. Sorry!

No developer resources to fix this currently.

**Comment by WilliamBonvini** [comment]
Hello there, how has this been solved?
