### ISSUE TITLE
Is log-likelihood calculation irrelavant with gibbs sampling?

### ISSUE THREAD

**Issue by Hins** [lda-project/lda#96]
IMHO, log-likelihood calculation is irrelavant with Gibbs sampling, finanlly LDA can get topic-word distribution, document-topic distribution and topic distribution by sampling w/o log-likelihood calculation.

**Comment by ariddell** [comment]
Are you talking about held-out log likelihood calculations (i.e., the probability of an unseen document)? In this case, we need to estimate the document-topic distribution for the unseen document. We do not know that in advance.
